artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
#  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip
  dataset_csv_file_path : artifacts/winequality-red.csv
  database_name  : dataset.db
  tabel_name : Raw_Wine_dataset
  extract_table_name : wine_extracted_data


data_validation:
  root_dir: artifacts/data_validation
  dataset_path: artifacts/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_preparation:
  root_dir: artifacts/data_preparation
  dataset_path: artifacts/winequality-red.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_preparation/dataset_prepared.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_df.csv
  test_data_path: artifacts/data_transformation/test_df.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json






